// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VerifyUIClient is the client API for VerifyUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifyUIClient interface {
	// ListEngineSpecs returns a list of Verify Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (VerifyUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type verifyUIClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifyUIClient(cc grpc.ClientConnInterface) VerifyUIClient {
	return &verifyUIClient{cc}
}

func (c *verifyUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (VerifyUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VerifyUI_ServiceDesc.Streams[0], "/v1.VerifyUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &verifyUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VerifyUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type verifyUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *verifyUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *verifyUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.VerifyUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyUIServer is the server API for VerifyUI service.
// All implementations must embed UnimplementedVerifyUIServer
// for forward compatibility
type VerifyUIServer interface {
	// ListEngineSpecs returns a list of Verify Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, VerifyUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedVerifyUIServer()
}

// UnimplementedVerifyUIServer must be embedded to have forward compatible implementations.
type UnimplementedVerifyUIServer struct {
}

func (UnimplementedVerifyUIServer) ListEngineSpecs(*ListEngineSpecsRequest, VerifyUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedVerifyUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedVerifyUIServer) mustEmbedUnimplementedVerifyUIServer() {}

// UnsafeVerifyUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifyUIServer will
// result in compilation errors.
type UnsafeVerifyUIServer interface {
	mustEmbedUnimplementedVerifyUIServer()
}

func RegisterVerifyUIServer(s grpc.ServiceRegistrar, srv VerifyUIServer) {
	s.RegisterService(&VerifyUI_ServiceDesc, srv)
}

func _VerifyUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VerifyUIServer).ListEngineSpecs(m, &verifyUIListEngineSpecsServer{stream})
}

type VerifyUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type verifyUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *verifyUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VerifyUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VerifyUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifyUI_ServiceDesc is the grpc.ServiceDesc for VerifyUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifyUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VerifyUI",
	HandlerType: (*VerifyUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _VerifyUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _VerifyUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "verify-ui.proto",
}
